# Generated by Django 5.2.3 on 2025-07-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_request_reset_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
