# Generated by Django 5.2.3 on 2025-07-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_otp_request_reset_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
