# Generated by Django 5.2.3 on 2025-07-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=1, help_text='Tell us about yourself, your goals, passions, or interests.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='topic',
            field=models.CharField(default='Not Specified', help_text='What are you interested in? (e.g. Web Development, Freelancing, etc.)', max_length=100),
            preserve_default=False,
        ),
    ]
