# Generated by Django 5.2.3 on 2025-07-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='topic',
            new_name='sport_coach',
        ),
    ]
