# Generated by Django 5.2.3 on 2025-07-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_description_user_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='details',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sport_coach',
        ),
    ]
