# Generated by Django 5.2.4 on 2025-07-08 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chat_plan'),
        ('plans', '0002_remove_plan_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='chat.chat'),
        ),
    ]
