# Generated by Django 5.2.4 on 2025-07-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plan_is_pinned_plan_plan_type_contact_plan_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
