# Generated by Django 5.2.4 on 2025-07-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_plan_chat_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
