# Generated by Django 5.2.4 on 2025-07-08 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('plans', '0002_remove_plan_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='plans.plan'),
        ),
    ]
