# Generated by Django 5.2.4 on 2025-07-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='plan',
        ),
    ]
