# Generated by Django 5.2.4 on 2025-07-08 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_coach', models.CharField(help_text='What are you interested in? (e.g. Web Development, Freelancing, etc.)', max_length=100)),
                ('details', models.TextField(help_text='Tell us about yourself, your goals, passions, or interests.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
